### ISSUE TITLE
What are the advantages of this work compared to prompt tuning?

### ISSUE THREAD

**Issue by Baboom-l** [DongSky/MR-GDINO#1]
As far as I know, prompt tuning performs well on grounding Dino and there is no forgetting problem.

**Comment by DongSky** [comment]
According to  our paper as well as a prior work (ZiRa-GroundingDINO [1]), vanilla PEFT-based method (including prompt tuning) still faces catastrophic forgetting issue in terms of unseen classes (open-world detection), though it might be helpful for seen classes in detection.
[1] Zero-shot Generalizable Incremental Learning for Vision-Language Object Detection, NeurIPS 2024

**Comment by Baboom-l** [comment]
You may not be familiar with the use of prompt tuning in open set detection, which only fine tunes some vectors to replace the output of the text encoder. Since it does not involve model parameter adjustment, there will be no forgetting on unseen classes

**Comment by DongSky** [comment]
However, in practical applications, the model still faces the difficulty for whether loading PEFT modules for inference or not (i.e., traditional zero-shot detection) in specific scenarios (which include  known / unknown domains  & objects). If using brute-force inference with continually learned PEFT modules, The performance on unseen categories will be affected.

**Comment by 1170300714** [comment]
Thank you for your reply. However, the community has long demonstrated that simply using prompt tuning (whether applied on the text side or the visual side) cannot solve the problem of catastrophic forgetting on old classes[1][2] or unseen classes[4][5]. 
For example, some additional anti-forgetting strategies are necessary.
[1] Learning to Prompt for Continual Learning
[2] AttriCLIP: A Non-Incremental Learner for Incremental Knowledge Learning
[4] Conditional Prompt Learning for Vision-Language Models
[5] Prompt-aligned Gradient for Prompt Tuning.

**Comment by 1170300714** [comment]
> You may not be familiar with the use of prompt tuning in open set detection, which only fine tunes some vectors to replace the output of the text encoder. Since it does not involve model parameter adjustment, there will be no forgetting on unseen classes

Thank you for your reply. However, the community has long demonstrated that simply using prompt tuning (whether applied on the text side or the visual side) cannot solve the problem of catastrophic forgetting on old classes[1][2] or unseen classes[3][4]. Some additional anti-forgetting strategies are necessary.
[1] Learning to Prompt for Continual Learning
[2] AttriCLIP: A Non-Incremental Learner for Incremental Knowledge Learning
[3] Conditional Prompt Learning for Vision-Language Models
[4] Prompt-aligned Gradient for Prompt Tuning.

**Comment by Baboom-l** [comment]
It seems that you don't know how prompt tuning is implemented in open-set detection. You can check [GLIP](https://github.com/microsoft/GLIP/tree/main),  [mmdet PR](https://github.com/open-mmlab/mmdetection/pull/11496/files#diff-328c33429117547fb5889f1bd29c40f59dcd5e7a27be7758c01fc59c1808270e) for details. The product obtained from the prompt tuning resembles the encoded_text portion of your code and corresponds to each of the fine-tuned classes, which are loaded as needed during inference. The unseen and old classes still output encoded_text through BERT

**Comment by 1170300714** [comment]
收到，感谢您的来件

**Comment by Baboom-l** [comment]
In my experience with this prompt tuning approach, I haven't encountered any forgetfulness problem in extending new classes, and the new class APs are good enough to compete with the full model fine-tuning on GLIP and Grounding DINO.

**Comment by Baboom-l** [comment]
Of course, this prompt tuning approach does not perform well on smaller models.
If your approach on small models like YOLO World-L can make the expanded new classes behave similarly to full fine-tuning with less forgetting, I would consider it a good job.

**Comment by 1170300714** [comment]
> In my experience with this prompt tuning approach, I haven't encountered any forgetfulness problem in extending new classes, and the new class APs are good enough to compete with the full model fine-tuning on GLIP and Grounding DINO.

Thank you for your reply.
1. In our setting, _unseen classes_ and _new classes_ are two distinct concepts. _New classes_ refer to the classes with training data available in each step (or task), while _unseen classes_ refer to those not included in any of the encountered classes (i.e., **they do not belong to any of the old classes or the new classes introduced in the current step**). Prompt tuning can effectively help the model learn _new classes_; however, its capability to handle _unseen classes_ does indeed decline[1].
2. Through our **experiments, combined with findings from existing studies in the community**, it appears that whether prompt tuning leads to forgetting is not related to the size of the base model. However, we hypothesize that it might be related to the **scale of the training set** (a finding also observed in non-ViT-based continual learning methods[2]). The smaller the training set and the fewer the number of classes, the more likely the prompt is to overfit to the new classes, thereby forgetting the old and unseen classes. It is important to highlight that o**ur method specifically targets such few-shot scenarios**, where each new class has only a very limited number of training samples. In these cases, relying solely on naive prompt tuning techniques inevitably leads to catastrophic forgetting.

[1] CoCoOp: Conditional Prompt Learning for Vision-Language Models
[2]  Few-Shot Class-Incremental Learning

**Comment by Baboom-l** [comment]
开集检测里用的提示微调和你说的不是一个东西。你应该知道grounding dino这类模型输入“dog.person”，会由bert编码得到文本特征2*768（举例)，模型通过这两个向量去检测dog和person。开集检测的提示微调会用一个2*768的向量替代这个文本特征，并仅优化这个向量，微调后存储为pth使用，一个1*768的向量对应一个类别。假设训练的新类是dog.person使用时加载即可，而不使用这微调类时，还是使用bert输出的文本特征，原理上就不应该存在遗忘问题。

**Comment by 1170300714** [comment]
> 开集检测里用的提示微调和你说的不是一个东西。你应该知道grounding dino这类模型输入“dog.person”，会由bert编码得到文本特征2_768（举例)，模型通过这两个向量去检测dog和person。开集检测的提示微调会用一个2_768的向量替代这个文本特征，并仅优化这个向量，微调后存储为pth使用，一个1*768的向量对应一个类别。假设训练的新类是dog.person使用时加载即可，而不使用这微调类时，还是使用bert输出的文本特征，原理上就不应该存在遗忘问题。

我们参考连续学习中最困难的情况，即“类增量”式的连续学习。在这类增量的设置下，inference时是无法提前预知测试图像究竟是旧类，新类，还是未见过的类别，因此无法直接判断是否使用prompt。这一点和您所说的场景不同

**Comment by Baboom-l** [comment]
> > 开集检测里用的提示微调和你说的不是一个东西。你应该知道grounding dino这类模型输入“dog.person”，会由bert编码得到文本特征2_768（举例)，模型通过这两个向量去检测dog和person。开集检测的提示微调会用一个2_768的向量替代这个文本特征，并仅优化这个向量，微调后存储为pth使用，一个1*768的向量对应一个类别。假设训练的新类是dog.person使用时加载即可，而不使用这微调类时，还是使用bert输出的文本特征，原理上就不应该存在遗忘问题。
> 
> 我们参考连续学习中最困难的情况，即“类增量”式的连续学习。在这类增量的设置下，inference时是无法提前预知测试图像究竟是旧类，新类，还是未见过的类别，因此无法直接判断是否使用prompt。这一点和您所说的场景不同

那你们推理时不需要设置类别，把类别标签改为生成式的方法了？据我所知grounding dino类模型是需要预设类别才能执行推理的，使用方式是需要设置类别文本后，再对一批或一张图像执行推理

**Comment by cafelattey** [comment]
> > 开集检测里用的提示微调和你说的不是一个东西。你应该知道grounding dino这类模型输入“dog.person”，会由bert编码得到文本特征2_768（举例)，模型通过这两个向量去检测dog和person。开集检测的提示微调会用一个2_768的向量替代这个文本特征，并仅优化这个向量，微调后存储为pth使用，一个1*768的向量对应一个类别。假设训练的新类是dog.person使用时加载即可，而不使用这微调类时，还是使用bert输出的文本特征，原理上就不应该存在遗忘问题。
> 
> 我们参考连续学习中最困难的情况，即“类增量”式的连续学习。在这类增量的设置下，inference时是无法提前预知测试图像究竟是旧类，新类，还是未见过的类别，因此无法直接判断是否使用prompt。这一点和您所说的场景不同

其实主要是这个定义的任务本身是可以用提示词微调完成的，打个比方我GDino在COCO上很棒，现在我要在PascalVOC上也要很好，那我类似于VPT[1]那样加入一个可训练提示，专门针对这个下游数据集训练这个提示即可，我不需要动整个模型我在COCO的表现自然不会掉，下次我要在COCO上跑我不加载这个提示就好，在Pascal上跑就加载，这样针对每个确定的任务其实训练一个提示就OK。他是另一种方法，但我认为可以解决你们提出的任务，除非论文里能让我看到对比说他的表现掉在了哪里，或者说你这个定义的任务为啥提示词微调无法完成，但我好像没看到相关表格？其实你们的baseline的Zira在openreview上好像也没有评审提出说为啥不比提示词微调的方法？我比较疑惑，要是你们能解答我的疑惑我会很感谢的。

[1]Jia, Menglin, et al. "Visual prompt tuning." European Conference on Computer Vision. Cham: Springer Nature Switzerland, 2022.

**Comment by cafelattey** [comment]
> > 开集检测里用的提示微调和你说的不是一个东西。你应该知道grounding dino这类模型输入“dog.person”，会由bert编码得到文本特征2_768（举例)，模型通过这两个向量去检测dog和person。开集检测的提示微调会用一个2_768的向量替代这个文本特征，并仅优化这个向量，微调后存储为pth使用，一个1*768的向量对应一个类别。假设训练的新类是dog.person使用时加载即可，而不使用这微调类时，还是使用bert输出的文本特征，原理上就不应该存在遗忘问题。
> 
> 我们参考连续学习中最困难的情况，即“类增量”式的连续学习。在这类增量的设置下，inference时是无法提前预知测试图像究竟是旧类，新类，还是未见过的类别，因此无法直接判断是否使用prompt。这一点和您所说的场景不同

然后baboom老哥的意思应该是GDino这个玩意是要提前喂提示词给他的，既然都知道了提示词，下游是啥任务应当也是明确的，其实不太存在说我不知道是否要加载prompt的情况，这也是我疑惑的点，感谢您解答

**Comment by 1170300714** [comment]
> > > 开集检测里用的提示微调和你说的不是一个东西。你应该知道grounding dino这类模型输入“dog.person”，会由bert编码得到文本特征2_768（举例)，模型通过这两个向量去检测dog和person。开集检测的提示微调会用一个2_768的向量替代这个文本特征，并仅优化这个向量，微调后存储为pth使用，一个1*768的向量对应一个类别。假设训练的新类是dog.person使用时加载即可，而不使用这微调类时，还是使用bert输出的文本特征，原理上就不应该存在遗忘问题。
> > 
> > 
> > 我们参考连续学习中最困难的情况，即“类增量”式的连续学习。在这类增量的设置下，inference时是无法提前预知测试图像究竟是旧类，新类，还是未见过的类别，因此无法直接判断是否使用prompt。这一点和您所说的场景不同
> 
> 然后baboom老哥的意思应该是GDino这个玩意是要提前喂提示词给他的，既然都知道了提示词，下游是啥任务应当也是明确的，其实不太存在说我不知道是否要加载prompt的情况，这也是我疑惑的点，感谢您解答

谢谢您的关注。我们的任务设置更多参考的是类增量学习中的测试时的设置，在类增量学习中的测试阶段，给定一张图像，我只能知道这张图像的类别属于旧类和新类空间的并集，但不知道他具体来自哪个任务。在我们的设置中的测试阶段，给定一张图像，我们只能知道这张图片一定属于旧类，新类，以及未知类（未知类的类别空间我们用lvis的类别空间指代，其实严格来说未知类的类别空间是可以接近于无穷多的）。因此，我们在测试时，不论测试的图像是来自哪个集合，G-DINO的输入的text类别空间都是“到目前为止的旧类”+“本task的新类”+“lvis的未知类”（且这个类别空间会随着任务的不断进行而不断增多）。而对于您说的那种情况更像是现有的现有的纯开放域学习工作，没有考虑到已知的旧类

**Comment by 1170300714** [comment]
> > > 开集检测里用的提示微调和你说的不是一个东西。你应该知道grounding dino这类模型输入“dog.person”，会由bert编码得到文本特征2_768（举例)，模型通过这两个向量去检测dog和person。开集检测的提示微调会用一个2_768的向量替代这个文本特征，并仅优化这个向量，微调后存储为pth使用，一个1*768的向量对应一个类别。假设训练的新类是dog.person使用时加载即可，而不使用这微调类时，还是使用bert输出的文本特征，原理上就不应该存在遗忘问题。
> > 
> > 
> > 我们参考连续学习中最困难的情况，即“类增量”式的连续学习。在这类增量的设置下，inference时是无法提前预知测试图像究竟是旧类，新类，还是未见过的类别，因此无法直接判断是否使用prompt。这一点和您所说的场景不同
> 
> 那你们推理时不需要设置类别，把类别标签改为生成式的方法了？据我所知grounding dino类模型是需要预设类别才能执行推理的，使用方式是需要设置类别文本后，再对一批或一张图像执行推理

我们依然需要设置类别，但我们设置类别的方法和传统的开放词汇学习的工作不同。我们在测试时，我们假设不知道到来的图像属于哪个集合（旧类集，新类集或未知类集）。因此，不论测试的图像是来自哪个集合，G-DINO的输入的text类别空间都将设置为“到目前为止的旧类”+“本task的新类”+“lvis的未知类”（且这个类别空间会随着任务的不断进行而不断增多）。这个推理的难度要比传统的开放域学习的难度更难，因为类别空间更大。若测试的图像恰好为旧类，那么本task的新类的空间和未知类空间就是干扰项，若测试图像是未知类，则旧类和本task的新类空间就是干扰项

**Comment by cafelattey** [comment]
> > > > 开集检测里用的提示微调和你说的不是一个东西。你应该知道grounding dino这类模型输入“dog.person”，会由bert编码得到文本特征2_768（举例)，模型通过这两个向量去检测dog和person。开集检测的提示微调会用一个2_768的向量替代这个文本特征，并仅优化这个向量，微调后存储为pth使用，一个1*768的向量对应一个类别。假设训练的新类是dog.person使用时加载即可，而不使用这微调类时，还是使用bert输出的文本特征，原理上就不应该存在遗忘问题。
> > > 
> > > 
> > > 我们参考连续学习中最困难的情况，即“类增量”式的连续学习。在这类增量的设置下，inference时是无法提前预知测试图像究竟是旧类，新类，还是未见过的类别，因此无法直接判断是否使用prompt。这一点和您所说的场景不同
> > 
> > 
> > 然后baboom老哥的意思应该是GDino这个玩意是要提前喂提示词给他的，既然都知道了提示词，下游是啥任务应当也是明确的，其实不太存在说我不知道是否要加载prompt的情况，这也是我疑惑的点，感谢您解答
> 
> 谢谢您的关注。我们的任务设置更多参考的是类增量学习中的测试时的设置，在类增量学习中的测试阶段，给定一张图像，我只能知道这张图像的类别属于旧类和新类空间的并集，但不知道他具体来自哪个任务。在我们的设置中的测试阶段，给定一张图像，我们只能知道这张图片一定属于旧类，新类，以及未知类（未知类的类别空间我们用lvis的类别空间指代，其实严格来说未知类的类别空间是可以接近于无穷多的）。因此，我们在测试时，不论测试的图像是来自哪个集合，G-DINO的输入的text类别空间都是“到目前为止的旧类”+“本task的新类”+“lvis的未知类”（且这个类别空间会随着任务的不断进行而不断增多）。而对于您说的那种情况更像是现有的现有的纯开放域学习工作，没有考虑到已知的旧类

OK,那我理解这句话的意思，就比如在我给的例子里，可能Pascal和COCO这俩数据集里都有’人‘这个类，然后来一张图我要检人，我也不是很确定我要不要去读我给pascal调的这个权重，工作的意义主要是在这些setting下？

**Comment by cafelattey** [comment]
> > > > 开集检测里用的提示微调和你说的不是一个东西。你应该知道grounding dino这类模型输入“dog.person”，会由bert编码得到文本特征2_768（举例)，模型通过这两个向量去检测dog和person。开集检测的提示微调会用一个2_768的向量替代这个文本特征，并仅优化这个向量，微调后存储为pth使用，一个1*768的向量对应一个类别。假设训练的新类是dog.person使用时加载即可，而不使用这微调类时，还是使用bert输出的文本特征，原理上就不应该存在遗忘问题。
> > > 
> > > 
> > > 我们参考连续学习中最困难的情况，即“类增量”式的连续学习。在这类增量的设置下，inference时是无法提前预知测试图像究竟是旧类，新类，还是未见过的类别，因此无法直接判断是否使用prompt。这一点和您所说的场景不同
> > 
> > 
> > 然后baboom老哥的意思应该是GDino这个玩意是要提前喂提示词给他的，既然都知道了提示词，下游是啥任务应当也是明确的，其实不太存在说我不知道是否要加载prompt的情况，这也是我疑惑的点，感谢您解答
> 
> 谢谢您的关注。我们的任务设置更多参考的是类增量学习中的测试时的设置，在类增量学习中的测试阶段，给定一张图像，我只能知道这张图像的类别属于旧类和新类空间的并集，但不知道他具体来自哪个任务。在我们的设置中的测试阶段，给定一张图像，我们只能知道这张图片一定属于旧类，新类，以及未知类（未知类的类别空间我们用lvis的类别空间指代，其实严格来说未知类的类别空间是可以接近于无穷多的）。因此，我们在测试时，不论测试的图像是来自哪个集合，G-DINO的输入的text类别空间都是“到目前为止的旧类”+“本task的新类”+“lvis的未知类”（且这个类别空间会随着任务的不断进行而不断增多）。而对于您说的那种情况更像是现有的现有的纯开放域学习工作，没有考虑到已知的旧类

OK,那我理解这句话的意思，就比如在我给的例子里，可能Pascal和COCO这俩数据集里都有’人‘这个类，然后来一张图我要检人，我也不是很确定我要不要去读我给pascal调的这个权重，工作的意义主要是在这些setting下？

**Comment by 1170300714** [comment]
> > > > > 开集检测里用的提示微调和你说的不是一个东西。你应该知道grounding dino这类模型输入“dog.person”，会由bert编码得到文本特征2_768（举例)，模型通过这两个向量去检测dog和person。开集检测的提示微调会用一个2_768的向量替代这个文本特征，并仅优化这个向量，微调后存储为pth使用，一个1*768的向量对应一个类别。假设训练的新类是dog.person使用时加载即可，而不使用这微调类时，还是使用bert输出的文本特征，原理上就不应该存在遗忘问题。
> > > > 
> > > > 
> > > > 我们参考连续学习中最困难的情况，即“类增量”式的连续学习。在这类增量的设置下，inference时是无法提前预知测试图像究竟是旧类，新类，还是未见过的类别，因此无法直接判断是否使用prompt。这一点和您所说的场景不同
> > > 
> > > 
> > > 然后baboom老哥的意思应该是GDino这个玩意是要提前喂提示词给他的，既然都知道了提示词，下游是啥任务应当也是明确的，其实不太存在说我不知道是否要加载prompt的情况，这也是我疑惑的点，感谢您解答
> > 
> > 
> > 谢谢您的关注。我们的任务设置更多参考的是类增量学习中的测试时的设置，在类增量学习中的测试阶段，给定一张图像，我只能知道这张图像的类别属于旧类和新类空间的并集，但不知道他具体来自哪个任务。在我们的设置中的测试阶段，给定一张图像，我们只能知道这张图片一定属于旧类，新类，以及未知类（未知类的类别空间我们用lvis的类别空间指代，其实严格来说未知类的类别空间是可以接近于无穷多的）。因此，我们在测试时，不论测试的图像是来自哪个集合，G-DINO的输入的text类别空间都是“到目前为止的旧类”+“本task的新类”+“lvis的未知类”（且这个类别空间会随着任务的不断进行而不断增多）。而对于您说的那种情况更像是现有的现有的纯开放域学习工作，没有考虑到已知的旧类
> 
> OK,那我理解这句话的意思，就比如在我给的例子里，可能Pascal和COCO这俩数据集里都有’人‘这个类，然后来一张图我要检人，我也不是很确定我要不要去读我给pascal调的这个权重，工作的意义主要是在这些setting下？

是的

**Comment by Baboom-l** [comment]
> > > > 开集检测里用的提示微调和你说的不是一个东西。你应该知道grounding dino这类模型输入“dog.person”，会由bert编码得到文本特征2_768（举例)，模型通过这两个向量去检测dog和person。开集检测的提示微调会用一个2_768的向量替代这个文本特征，并仅优化这个向量，微调后存储为pth使用，一个1*768的向量对应一个类别。假设训练的新类是dog.person使用时加载即可，而不使用这微调类时，还是使用bert输出的文本特征，原理上就不应该存在遗忘问题。
> > > 
> > > 
> > > 我们参考连续学习中最困难的情况，即“类增量”式的连续学习。在这类增量的设置下，inference时是无法提前预知测试图像究竟是旧类，新类，还是未见过的类别，因此无法直接判断是否使用prompt。这一点和您所说的场景不同
> > 
> > 
> > 那你们推理时不需要设置类别，把类别标签改为生成式的方法了？据我所知grounding dino类模型是需要预设类别才能执行推理的，使用方式是需要设置类别文本后，再对一批或一张图像执行推理
> 
> 我们依然需要设置类别，但我们设置类别的方法和传统的开放词汇学习的工作不同。我们在测试时，我们假设不知道到来的图像属于哪个集合（旧类集，新类集或未知类集）。因此，不论测试的图像是来自哪个集合，G-DINO的输入的text类别空间都将设置为“到目前为止的旧类”+“本task的新类”+“lvis的未知类”（且这个类别空间会随着任务的不断进行而不断增多）。这个推理的难度要比传统的开放域学习的难度更难，因为类别空间更大。若测试的图像恰好为旧类，那么本task的新类的空间和未知类空间就是干扰项，若测试图像是未知类，则旧类和本task的新类空间就是干扰项

感谢您的回复。如果输入的text类别空间不断扩充，即使不是新类，而是预训练数据中的旧类添加进去，原本数据集的指标也会存在波动(因为GD中存在图文Bi融合，新增的类特征其实会影响图像特征)，这个问题您那边是如何解决的呢，比如O365和COCO两个数据集，当我向COCO的完整的类别文本空间中再加入一些O365的类别，COCO测试的指标会出现明显变化(通常是下降)。您的方法是否也适用于解决这个问题呢

**Comment by hengseuer** [comment]
> > > > > 开集检测里用的提示微调和你说的不是一个东西。你应该知道grounding dino这类模型输入“dog.person”，会由bert编码得到文本特征2_768（举例)，模型通过这两个向量去检测dog和person。开集检测的提示微调会用一个2_768的向量替代这个文本特征，并仅优化这个向量，微调后存储为pth使用，一个1*768的向量对应一个类别。假设训练的新类是dog.person使用时加载即可，而不使用这微调类时，还是使用bert输出的文本特征，原理上就不应该存在遗忘问题。
> > > > 
> > > > 
> > > > 我们参考连续学习中最困难的情况，即“类增量”式的连续学习。在这类增量的设置下，inference时是无法提前预知测试图像究竟是旧类，新类，还是未见过的类别，因此无法直接判断是否使用prompt。这一点和您所说的场景不同
> > > 
> > > 
> > > 那你们推理时不需要设置类别，把类别标签改为生成式的方法了？据我所知grounding dino类模型是需要预设类别才能执行推理的，使用方式是需要设置类别文本后，再对一批或一张图像执行推理
> > 
> > 
> > 我们依然需要设置类别，但我们设置类别的方法和传统的开放词汇学习的工作不同。我们在测试时，我们假设不知道到来的图像属于哪个集合（旧类集，新类集或未知类集）。因此，不论测试的图像是来自哪个集合，G-DINO的输入的text类别空间都将设置为“到目前为止的旧类”+“本task的新类”+“lvis的未知类”（且这个类别空间会随着任务的不断进行而不断增多）。这个推理的难度要比传统的开放域学习的难度更难，因为类别空间更大。若测试的图像恰好为旧类，那么本task的新类的空间和未知类空间就是干扰项，若测试图像是未知类，则旧类和本task的新类空间就是干扰项
> 
> 感谢您的回复。如果输入的text类别空间不断扩充，即使不是新类，而是预训练数据中的旧类添加进去，原本数据集的指标也会存在波动(因为GD中存在图文Bi融合，新增的类特征其实会影响图像特征)，这个问题您那边是如何解决的呢，比如O365和COCO两个数据集，当我向COCO的完整的类别文本空间中再加入一些O365的类别，COCO测试的指标会出现明显变化(通常是下降)。您的方法是否也适用于解决这个问题呢

The feature enhancer is a double-edged sword. On the one hand, it can improve the score of the true positive, but also may lead to false positive.
